#!/usr/bin/python
# vim:set ts=4 sw=4 et:
from __future__ import (absolute_import, division, print_function,
        unicode_literals)
import sys
import os.path
from ConfigParser import SafeConfigParser

PYTHON_BASE_PATH = os.path.join(
        os.path.abspath(os.path.dirname(sys.argv[0])), b'src')
sys.path.insert(0, PYTHON_BASE_PATH)

from pba.core.gpio import *
from pba.core.sprinkler_config import load_sprinklers

def setup_sprinkler(sprinkler_name, sprinkler):
    if not sprinkler.is_setup:
        print("setting up {}".format(sprinkler))
        sprinkler.setup()
    else:
        print("skipping set-up of {}".format(sprinkler))

def main(config):
    gpio_ctrl = GpioController()
    load_sprinklers(config, gpio_ctrl, setup_sprinkler)

if __name__ == '__main__':
    config = SafeConfigParser()
    config.read(sys.argv[1])
    main(config)
